#!/bin/sh
set -e

if [ ! -f /usr/lib/nginx/modules/ngx_http_lua_module.so ]; then
  # Skip the test if ngx_http_lua_module.so doesn't exist
  exit 77
fi

cat <<EOF > "/etc/nginx/sites-enabled/default"
server {
  listen 80 default_server;

  location /t {
    content_by_lua_block {
      local utils = require "resty.core.utils"

      local strings = {
        "Header_Name",
        "_Header_Name_",
        "Header__Name",
        "Header-Name",
        "Hello world",
      }

      for i = 1, #strings do
        ngx.say(utils.str_replace_char(strings[i], "_", "-"))
      end
    }
  }
}
EOF

exp="Header-Name
-Header-Name-
Header--Name
Header-Name
Hello world
response_code: 200"

nginx -t
invoke-rc.d nginx restart || { journalctl -n all -xu nginx.service; exit 1; }

out=`curl --fail -w "response_code: %{http_code}\n" http://127.0.0.1/t`

if [ x"${out}" != x"${exp}" ]; then
  echo "output:"
  echo "====================="
  echo "${out}"
  echo "====================="
  echo "expected output:"
  echo "====================="
  echo "${exp}"
  echo "====================="
  exit 1
fi
exit 0
